### PR TITLE
Frontend to Main BugFix, Assignpage, Loading MUI component, Navbar navigation changes

### PR DESCRIPTION
**Pull request by natekrth**

### CODE REVIEW

**Review by panitnt — APPROVED** [review]
That's good!

**Review by panitnt — CHANGES_REQUESTED** [review]
Umm, I need to change something wrong to show on result page

**Review by panitnt — APPROVED** [review]
Now, I think it ready to merge. Approved

**Review by breezjirasak — APPROVED** [review]
Approved

**Pull request merged**
