### PR TITLE
Implement navbar

### PR DESCRIPTION
**Pull request by breezjirasak**
- Implement Horizontal NavBar.
- Implement Vertical NavBar.
- Implement Hamburger NavBar following screen width and screen height.

### CODE REVIEW

**Comment by natekrth** [comment]
Perfectly done but don't forget to put all the path in navbarContent.js @BeaverGroup/frontend-team

**Review by natekrth — APPROVED** [review]
Approved

**Review by panitnt — COMMENTED** [review]
Can you resize account svg to be larger?

**Comment by breezjirasak** [comment]
> Can you resize account svg to be larger?

I already increase the size. Pls take a look.

**Review by panitnt — APPROVED** [review]
Great! Go on

**Pull request merged**
