### PR TITLE
Frontend in to Main

### PR DESCRIPTION
**Pull request by natekrth**

### CODE REVIEW

**Review by panitnt — APPROVED** [review]
Good to go!

**Review by panitnt — CHANGES_REQUESTED** [review]
Can you remove all console log?

**Comment by geeegrace02** [comment]
Overall nice and completed!!!

**Review by breezjirasak — APPROVED** [review]
Niceeee

**Review by reviseUC73 — APPROVED** [review]
nice

**Review by panitnt — APPROVED** [review]
Good to go!

**Review by geeegrace02 — APPROVED** [review]
Overall nice and completed!!!

**Pull request merged**
